junit_history:
  #build: .
  image: gcr.io/chris-meyers/junit_history
  ports:
    - "8080:8080"
  volumes:
    - .:/jh
  links:
    - mongo
  working_dir: /jh/server
  entrypoint: "/usr/bin/dumb-init"
  command: ["npm", "run-script", "dev"]
  #command: ["npm", "start"]
mongo:
  image: mongo:3.0.2
