apiVersion: v1
kind: ReplicationController
metadata:
 labels:
   name: junit-history-app
 name: junit-history-app-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: junit-history-app
   spec:
     containers:
     - name: junit-history-app
       image: us.gcr.io/stoked-archway-645/junit_history
       ports:
       - containerPort: 3000
         name: http-server
