apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: junit-history-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: junit-history-app
    spec:
      containers:
       - name: junit-history-app
         image: gcr.io/chris-meyers/junit_history:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
           name: http-server
