apiVersion: v1
kind: Service
metadata:
 name: junit-history-app
 labels:
   name: junit-history-app
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 3000
     protocol: TCP
 selector:
   name: junit-history-app
